eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8772

spring:
  application:
    name: bootrmi-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 15
  redis:
    host: localhost
    port: 6379
    password: joeeeeeRedis
  profiles:
    include: config


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml



