msg:
    url: https://app.cloopen.com:8883/2013-12-26/Accounts/8a216da866f16d680166f5f772590246/SMS/TemplateSMS?sig=
    idToken: 8a216da866f16d680166f5f7725902461728cee24dc04d2e984cab1363387449
    sid: 8a216da866f16d680166f5f772590246
    params:
        appId: 8a216da866f16d680166f5f772b0024d
        templateId: 1

email:
    url: http://api.sendcloud.net/apiv2/mail/send
    apiUser: joee_test_ObRIzs
    apiKey: AercLSS3VYBK7fyL
    from: joeeeee@joeeeee.org
    fromName: Joeeeee
    subject: 验证邮件

pic:
    url: http://joeeeee.oss-cn-beijing.aliyuncs.com/usr/pic/
    resize: x-oss-process=image/resize,m_lfit,h_100,w_100